### ISSUE TITLE
"(eval):1: bad pattern: ^[[01" when adding a new bookmark

### ISSUE THREAD

**Issue by Hund** [EinfachToll/bom#1]
When I add a bookmark I get this output:

```
$ bom add backups
Created the bookmark ~backups for /media/HDD0/Backups/
(eval):1: bad pattern: ^[[01
$ cd ~backups
zsh: no such user or named directory: backups
```

And the bookmark doesn't work until I reload  my zshrc. What's wrong?

I'm running Arch Linux with 5.2.

**Comment by EinfachToll** [comment]
_sigh_ Oh, the joys of escaping in shells. I have not really an idea what could be wrong here, assuming your input contained no weird invisible characters. For me (zsh version 5.0.2), it works. I can only advice you to change the `eval` in the snippet you have put into your .zshrc into `echo`, reload the zsh, try again to add this bookmark and take a look at the output. It should look like this:

```
Created the bookmark ~backups for /media/HDD0/Backups/
hash -d backups="/media/HDD0/Backups/"
```

Copying the last line and directly executing it in the zsh should work, too.

**Comment by Hund** [comment]
That works. Thanks. :)

**Comment by EinfachToll** [comment]
Actually, my comment was not meant to be a solution or workaround, but a debugging step to see what happens. Anyway, if you execute this line manually and it works, and it doesn't work if you eval the very same line in the script, then I have not the slightest idea what could cause the error, so we might as well leave this issue closed ;)
